import Head from 'next/head'
import { motion, useAnimation } from 'framer-motion'
import { useInView } from 'react-intersection-observer'
import { Suspense, useEffect } from 'react'
import dynamic from 'next/dynamic'
import {
	Hero,
	Heading,
	Form,
	Divider,
	Features,
	Services,
	CookieBanner,
	Footer,
} from '../components/index.js'
import Image from 'next/image.js'
import image from '../public/solar-plant.webp'
import heroImage from '../public/hero-image.webp'

const fadeIn = {
	visible: { opacity: 1, scale: 1, transition: { duration: 0.3 } },
	hidden: { opacity: 0, scale: 1 },
}

const DynamicTestimonials = dynamic(
	() => import('../components/Testimonials'),
	{
		suspense: true,
	}
)

export default function Home() {
	const control = useAnimation()
	const [ref, inView] = useInView({})

	useEffect(() => {
		if (inView) {
			control.start('visible')
		}
		{
			/* later enable conditional fadein based on oberserver */
		}
		// else {
		// 	control.start('hidden')
		// }
	}, [control, inView])

	return (
		<>
			<Head>
				<title>JvG Thoma</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* TODO Add fadein for all divs*/}
			<div>
				<main className='w-full'>
					<div className='mx-auto max-w-md sm:max-w-xl w-full md:max-w-3xl py-6  sm:py-6 md:px-20 md:py-10'>
						<Image
							src={heroImage}
							alt='logo'
							layout='responsive'
							width={608}
							height={321}
							priority={true}
						/>
					</div>

					<div className='w-full border-box  pl-2 pr-2 '>
						<div className='mx-auto max-w-xl'>
							<motion.div
								className='wrapper break-words text-center text-textColor'
								ref={ref}
								variants={fadeIn}
								initial='hidden'
								animate={control}
							>
								<h2 className='text-4xl font-bold tracking-tight  sm:text-5xl  '>
									<strong>Make Profit with your own Solar Module Production Line</strong>
								</h2>
							</motion.div>
						</div>
						<motion.div
							ref={ref}
							variants={fadeIn}
							initial='hidden'
							animate={control}
						>
							<Form buttonText='Sign Up Now ' />
						</motion.div>
						<Divider />
						<Features />
						<Hero image={image} width='608' height='321' />
						<Services />
						<DynamicTestimonials />
						<Divider />
						<Heading text='Make Profit with your own Solar Module Production Line' />
						<Form buttonText='Sign Up Now ' />
					</div>
				</main>
				<Footer />
			</div>
		</>
	)
}
